local Global        = GCompute.GlobalNamespace
local Object        = Global:AddType ("Object")
local Type          = Global:AddType ("Type")
local Namespace     = Global:AddType ("Namespace")
local Function      = Global:AddType ("Function")
local FunctionGroup = Global:AddType ("FunctionGroup")

local Void          = Global:AddType ("Void")
Void:SetIsBottom (true)
Global:GetTypeSystem ():SetBottom (Void)

local Boolean       = Global:AddType ("Boolean")
local Number        = Global:AddType ("Number")
local Integer       = Global:AddType ("Integer")
local String        = Global:AddType ("String")

Global:AddAlias ("object",  "Object")
Global:AddAlias ("type",    "Type")
Global:AddAlias ("void",    "Void")
Global:AddAlias ("bool",    "Boolean")
Global:AddAlias ("boolean", "Boolean")
Global:AddAlias ("number",  "Number")
Global:AddAlias ("double",  "Number")
Global:AddAlias ("int",     "Integer")
Global:AddAlias ("string",  "String")