function GCompute.IDE.MenuStrip (self)
	local menuStrip = vgui.Create ("GMenuStrip", self)
	
	local fileMenu = menuStrip:AddMenu ("File")
	fileMenu:AddItem ("New")
		:SetAction ("New")
	fileMenu:AddItem ("Open")
		:SetAction ("Open")
	fileMenu:AddItem ("Save")
		:SetAction ("Save")
	fileMenu:AddItem ("Save As...")
		:SetAction ("Save As")
	fileMenu:AddItem ("Save All")
		:SetAction ("Save All")
	fileMenu:AddItem ("Close")
		:SetAction ("Close")
	fileMenu:AddSeparator ()
	fileMenu:AddItem ("Exit")
		:SetAction ("Exit")
	
	local editMenu = menuStrip:AddMenu ("Edit")
	editMenu:AddItem ("Undo")
		:SetIcon ("icon16/arrow_undo.png")
	editMenu:AddItem ("Redo")
		:SetIcon ("icon16/arrow_redo.png")
	editMenu:AddSeparator ()
	editMenu:AddItem ("Cut")
		:SetAction ("Cut")
	editMenu:AddItem ("Copy")
		:SetAction ("Copy")
	editMenu:AddItem ("Paste")
		:SetAction ("Paste")
	editMenu:AddItem ("Select All")
		:SetAction ("Select All")
	
	local toolsMenu = menuStrip:AddMenu ("View")
	toolsMenu:AddItem ("Console")
		:SetAction ("Console")
	toolsMenu:AddItem ("Output")
		:SetAction ("Output")
	toolsMenu:AddItem ("File Browser")
		:SetAction ("FileBrowser")
	toolsMenu:AddItem ("Processes")
		:SetAction ("ProcessBrowser")
	toolsMenu:AddItem ("Profiler")
		:SetAction ("Profiler")
	toolsMenu:AddItem ("Hook Profiler")
		:SetAction ("HookProfiler")
	toolsMenu:AddItem ("Donation")
		:SetAction ("Donation")
	
	local toolsMenu = menuStrip:AddMenu ("Tools")
	toolsMenu:AddItem ("Settings")
		:SetAction ("Open Settings")
	
	local helpMenu = menuStrip:AddMenu ("Help")
	helpMenu:AddItem ("About")
		:SetAction ("Open About")
	
	return menuStrip
end