function GCompute.IDE.MenuStrip (self)
	local menuStrip = vgui.Create ("GMenuStrip", self)
	
	local fileMenu = menuStrip:AddMenu ("File")
	fileMenu:AddOption ("New")
		:SetIcon ("icon16/page_white_add.png")
		:SetAction ("New")
	fileMenu:AddOption ("Open")
		:SetIcon ("icon16/folder_page.png")
		:SetAction ("Open")
	fileMenu:AddOption ("Save")
		:SetIcon ("icon16/disk.png")
		:SetAction ("Save")
	fileMenu:AddOption ("Save As...")
		:SetIcon ("icon16/disk.png")
		:SetAction ("Save As")
	fileMenu:AddOption ("Save All")
		:SetIcon ("icon16/disk_multiple.png")
		:SetAction ("Save All")
	fileMenu:AddOption ("Close")
		:SetAction ("Close")
	fileMenu:AddSeparator ()
	fileMenu:AddOption ("Exit")
		:SetAction ("Exit")
	
	local editMenu = menuStrip:AddMenu ("Edit")
	editMenu:AddOption ("Undo")
		:SetIcon ("icon16/arrow_undo.png")
	editMenu:AddOption ("Redo")
		:SetIcon ("icon16/arrow_redo.png")
	editMenu:AddSeparator ()
	editMenu:AddOption ("Cut")
		:SetIcon ("icon16/cut.png")
		:SetAction ("Cut")
	editMenu:AddOption ("Copy")
		:SetIcon ("icon16/page_white_copy.png")
		:SetAction ("Copy")
	editMenu:AddOption ("Paste")
		:SetIcon ("icon16/paste_plain.png")
		:SetAction ("Paste")
	editMenu:AddOption ("Select All")
		:SetAction ("Select All")
	
	return menuStrip
end