function GCompute.IDE.MenuStrip (self)
	local menuStrip = vgui.Create ("GMenuStrip", self)
	
	local fileMenu = menuStrip:AddMenu ("File")
	fileMenu:AddOption ("New")
		:SetAction ("New")
	fileMenu:AddOption ("Open")
		:SetAction ("Open")
	fileMenu:AddOption ("Save")
		:SetAction ("Save")
	fileMenu:AddOption ("Save As...")
		:SetAction ("Save As")
	fileMenu:AddOption ("Save All")
		:SetAction ("Save All")
	fileMenu:AddOption ("Close")
		:SetAction ("Close")
	fileMenu:AddSeparator ()
	fileMenu:AddOption ("Exit")
		:SetAction ("Exit")
	
	local editMenu = menuStrip:AddMenu ("Edit")
	editMenu:AddOption ("Undo")
		:SetIcon ("icon16/arrow_undo.png")
	editMenu:AddOption ("Redo")
		:SetIcon ("icon16/arrow_redo.png")
	editMenu:AddSeparator ()
	editMenu:AddOption ("Cut")
		:SetAction ("Cut")
	editMenu:AddOption ("Copy")
		:SetAction ("Copy")
	editMenu:AddOption ("Paste")
		:SetAction ("Paste")
	editMenu:AddOption ("Select All")
		:SetAction ("Select All")
	
	local toolsMenu = menuStrip:AddMenu ("View")
	toolsMenu:AddOption ("Output")
		:SetAction ("Output")
	toolsMenu:AddOption ("Processes")
		:SetAction ("ProcessBrowser")
	toolsMenu:AddOption ("Hook Profiler")
		:SetAction ("HookProfiler")
	
	local toolsMenu = menuStrip:AddMenu ("Tools")
	toolsMenu:AddOption ("Settings")
		:SetAction ("Open Settings")
	
	local helpMenu = menuStrip:AddMenu ("Help")
	helpMenu:AddOption ("About")
		:SetAction ("Open About")
	
	return menuStrip
end